name: Cachix Push

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cachix.yml'
      - 'flake.lock'
      - 'flake.nix'
      - 'nix/**'
      - 'packages/**'

jobs:
  nix-flake:
    name: Nix Flake Check(for Cachix Push)
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: prepare nix
        uses: cachix/install-nix-action@v29
      - name: prepare cachix
        uses: cachix/cachix-action@v15
        with:
          name: times-yasunori
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: flake check
        run: nix flake check -L --accept-flake-config
